### PR TITLE
Ember 3.0

### PR DESCRIPTION
**Pull request by Exelord**

### CODE REVIEW

**Comment by Exelord** [comment]
As Ember 3.0 Has been release this work will continue :)

**Comment by Exelord** [comment]
Hey @st-h 
could you please confirm if this branch works correctly with Ember 3.0?

**Comment by Exelord** [comment]
In case of any problems, please raise an issue :)

**Comment by st-h** [comment]
@Exelord 0.7.0 looks good here. Thanks for the update 👍

**Pull request merged**
